name: scatter
description: A CLI tool for uploading Minecraft Mods to Modrinth, CurseForge and GitHub
version: 0.4.1
homepage: https://docs.wispforest.io/scatter/home/

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: 
  archive: ^3.1.6
  args: ^2.3.0
  build_runner: ^2.1.4
  collection: ^1.16.0
  console: ^4.1.0
  http: ^0.13.4
  http_parser: ^4.0.1
  io: ^1.0.3
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
  logging: ^1.0.2
  path: ^1.8.0
  toml: ^0.13.1
  uri: ^1.0.0
  version: ^3.0.2
