name: scatter
description: A CLI tool for uploading Minecraft Mods to Modrinth, CurseForge and GitHub
version: 0.5.0-pre.3
homepage: https://docs.wispforest.io/scatter/home/
publish_to: none

environment:
  sdk: '^3.0.1'

dev_dependencies:
  build_runner: ^2.4.4
  build_version: ^2.1.1
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.16.0
dependencies: 
  archive: ^3.1.6
  args: ^2.3.0
  dart_console: ^1.2.0
  http: ^1.0.0
  io: ^1.0.3
  json_annotation: ^4.8.1
  logging: ^1.0.2
  modrinth_api:
    git:
      url: https://github.com/gliscowo/modrinth_api
      ref: afeaa8c
  path: ^1.8.0
  pub_semver: ^2.1.4
  toml: ^0.14.0
  uri: ^1.0.0
